import type {
  LobbyConfig,
  FieldDefinition,
  FieldType,
} from '../../shared/types/config.types';

// ── SQL type map ────────────────────────────────────────

const SQL_TYPE: Record<FieldType, string> = {
  string: 'VARCHAR',
  number: 'NUMERIC',
  boolean: 'BOOLEAN',
};

// ── Initial setup migration ─────────────────────────────

/**
 * Generates the CREATE TABLE migration from lobby.config.json.
 * Called by "pnpm run setup".
 */
export function generateInitialMigration(config: LobbyConfig): string {
  const userColumns = Object.entries(config.waitlist.fields)
    .map(([name, def]) => {
      let type;
      if (def.type === 'string') {
        type = `VARCHAR(${def.maxLength || 255})`;
      } else {
        type = SQL_TYPE[def.type];
      }

      const constraint = def.required ? ' NOT NULL' : '';
      return `  ${name} ${type}${constraint}`;
    })
    .join(',\n');

  const userColumnsBlock = userColumns
    ? `,\n\n  -- fields defined during setup\n${userColumns}`
    : '';

  const privacyColumns = [
    ...(config.privacy.collectIp
      ? ['  ip_address             VARCHAR(45)']
      : []),
    ...(config.privacy.collectUserAgent
      ? ['  user_agent             VARCHAR(1024)']
      : []),
  ];
  const privacyBlock =
    privacyColumns.length > 0 ? `\n${privacyColumns.join(',\n')},` : '';

  return `-- Generated by Lobby setup. Do not edit manually.
-- Schema changes should be made via "pnpm run fields:add" or "pnpm run fields:edit".

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE SEQUENCE waitlist_position_seq START 1;

CREATE TABLE waitlist_entries (
  id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  email                  VARCHAR(320) NOT NULL UNIQUE,
  position               INTEGER     NOT NULL DEFAULT 0,${privacyBlock}
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()${userColumnsBlock}
);

-- Assigns the next available position before each insert using a sequence.
-- nextval() is atomic, so concurrent signups are guaranteed unique positions.
CREATE OR REPLACE FUNCTION lobby_assign_position()
RETURNS TRIGGER AS $$
BEGIN
  NEW.position := nextval('waitlist_position_seq');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_waitlist_position
  BEFORE INSERT ON waitlist_entries
  FOR EACH ROW EXECUTE FUNCTION lobby_assign_position();

-- Keeps updated_at current on every row change.
CREATE OR REPLACE FUNCTION lobby_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_waitlist_updated_at
  BEFORE UPDATE ON waitlist_entries
  FOR EACH ROW EXECUTE FUNCTION lobby_touch_updated_at();
`;
}

// ── Add columns migration ───────────────────────────────

/**
 * Generates ALTER TABLE ADD COLUMN statements for new fields.
 * Called by "pnpm run fields:add".
 */
export function generateAddColumnsMigration(
  fields: Record<string, FieldDefinition>
): string {
  let statements = '';
  for (const name in fields) {
    if (!Object.hasOwn(fields, name)) continue;

    const def = fields[name]!;
    const type =
      def.type === 'string'
        ? `VARCHAR(${def.maxLength || 255})`
        : SQL_TYPE[def.type];
    const constraint = def.required ? ' NOT NULL' : '';

    statements += `ALTER TABLE waitlist_entries ADD COLUMN IF NOT EXISTS ${name} ${type}${constraint};\n`;
  }

  return `-- Generated by "pnpm run fields:add"\n\n${statements}`;
}

// ── Edit columns migration ──────────────────────────────

export interface FieldEdit {
  name: string;
  old: FieldDefinition;
  new: FieldDefinition;
}

/**
 * Generates ALTER TABLE statements for edited fields.
 * Called by "pnpm run fields:edit".
 *
 * Handles two kinds of changes:
 *   1. Type change     — ALTER COLUMN name TYPE new_type
 *   2. Required change — ALTER COLUMN name SET/DROP NOT NULL
 *
 * Risky operations get a warning comment so the user knows what
 * to check before running migration:run.
 *
 * Returns null if nothing actually changed — callers use this
 * to skip file generation entirely.
 */
export function generateEditColumnsMigration(
  edits: FieldEdit[]
): string | null {
  const statements: string[] = [];

  for (const edit of edits) {
    const typeChanged = edit.old.type !== edit.new.type;
    const lengthChanged = edit.old.maxLength !== edit.new.maxLength;
    const requiredChanged = edit.old.required !== edit.new.required;

    if (!typeChanged && !lengthChanged && !requiredChanged) continue;

    if (typeChanged || lengthChanged) {
      let newSqlType = SQL_TYPE[edit.new.type];
      if (edit.new.type === 'string') {
        newSqlType = `VARCHAR(${edit.new.maxLength || 255})`;
      }
      statements.push(
        [
          `-- WARNING: Changing column type or length may fail if existing data cannot be cast to ${newSqlType}.`,
          `--          Back up your data before running this migration.`,
          `ALTER TABLE waitlist_entries ALTER COLUMN ${edit.name} TYPE ${newSqlType};`,
        ].join('\n')
      );
    }

    if (requiredChanged) {
      if (edit.new.required) {
        statements.push(
          [
            `-- WARNING: Setting NOT NULL will fail if any existing rows have NULL in "${edit.name}".`,
            `--          Ensure all rows have a value before running this migration.`,
            `ALTER TABLE waitlist_entries ALTER COLUMN ${edit.name} SET NOT NULL;`,
          ].join('\n')
        );
      } else {
        // Dropping NOT NULL is always safe — no warning needed
        statements.push(
          `ALTER TABLE waitlist_entries ALTER COLUMN ${edit.name} DROP NOT NULL;`
        );
      }
    }
  }

  if (statements.length === 0) return null;

  return `-- Generated by "pnpm run fields:edit"\n\n${statements.join('\n\n')}\n`;
}
