import type {
  LobbyConfig,
  FieldDefinition,
  FieldType,
  FieldValue,
} from '../../shared/types/config.types';
import { toSqlType } from './db-type-mapping';
import { WAITLIST_TABLE } from '../../shared/constants/database.constants';

// ── Interfaces ──────────────────────────────────────────

export interface FieldEdit {
  name: string;
  old: FieldDefinition;
  new: FieldDefinition;
  newName?: string;
}

export interface GeneratedMigration {
  sql: string;
  warnings: string[];
}

// ── Helpers ─────────────────────────────────────────────

/**
 * Converts a JS value to a SQL literal string, with proper escaping.
 * Used when embedding default values in generated migration statements.
 */
function toSqlLiteral(value: FieldValue, type: FieldType): string {
  switch (type) {
    case 'string': {
      if (typeof value !== 'string') {
        throw new Error(`Expected string default, got ${typeof value}`);
      }
      // Escape single quotes
      return `'${value.replace(/'/g, "''")}'`;
    }

    case 'number': {
      if (typeof value !== 'number' || !isFinite(value)) {
        throw new Error(`Expected finite number default, got ${value}`);
      }
      return String(value);
    }

    case 'boolean': {
      if (typeof value !== 'boolean') {
        throw new Error(`Expected boolean default, got ${typeof value}`);
      }
      return value ? 'TRUE' : 'FALSE';
    }

    default:
      throw new Error(`Unhandled FieldType: ${type}`);
  }
}

/**
 * Generates the CREATE TABLE migration from lobby.config.json.
 * Called by "pnpm run setup".
 */
export function generateInitialMigration(config: LobbyConfig): string {
  let userColumns = '';
  for (const [name, def] of Object.entries(config.waitlist.fields)) {
    const type = toSqlType(def);
    const constraint = def.required ? ' NOT NULL' : '';
    userColumns += userColumns
      ? `,\n  ${name} ${type}${constraint}`
      : `  ${name} ${type}${constraint}`;
  }

  const userColumnsBlock = userColumns
    ? `,\n\n  -- fields defined during setup\n${userColumns}`
    : '';

  const privacyColumns = [
    ...(config.privacy.collectIp
      ? ['  ip_address             VARCHAR(45)']
      : []),
    ...(config.privacy.collectUserAgent
      ? ['  user_agent             VARCHAR(1024)']
      : []),
  ];
  const privacyBlock =
    privacyColumns.length > 0 ? `\n${privacyColumns.join(',\n')},` : '';

  return `-- Generated by Lobby setup. Do not edit manually.
-- Schema changes should be made via "pnpm run fields:add" or "pnpm run fields:edit".

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE SEQUENCE waitlist_position_seq START 1;

CREATE TABLE ${WAITLIST_TABLE} (
  id                     UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  email                  VARCHAR(320) NOT NULL UNIQUE,
  position               INTEGER     NOT NULL DEFAULT 0,${privacyBlock}
  created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()${userColumnsBlock}
);

-- Assigns the next available position before each insert using a sequence.
-- nextval() is atomic, so concurrent signups are guaranteed unique positions.
CREATE OR REPLACE FUNCTION lobby_assign_position()
RETURNS TRIGGER AS $$
BEGIN
  NEW.position := nextval('waitlist_position_seq');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_waitlist_position
  BEFORE INSERT ON ${WAITLIST_TABLE}
  FOR EACH ROW EXECUTE FUNCTION lobby_assign_position();

-- Keeps updated_at current on every row change.
-- (Required for PostgreSQL because UPDATE does not touch updated_at automatically.)
CREATE OR REPLACE FUNCTION lobby_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_waitlist_updated_at
  BEFORE UPDATE ON ${WAITLIST_TABLE}
  FOR EACH ROW EXECUTE FUNCTION lobby_touch_updated_at();
`;
}

/**
 * Generates ALTER TABLE ADD COLUMN statements for new fields.
 * Called by "pnpm run fields:add".
 */
export function generateAddColumnsMigration(
  fields: Record<string, FieldDefinition>,
  defaults: Record<string, FieldValue> = {}
): GeneratedMigration {
  if (Object.keys(fields).length === 0) {
    return { sql: '', warnings: [] };
  }

  const statements: string[] = [];
  const warnings: string[] = [];

  for (const [name, def] of Object.entries(fields)) {
    const type = toSqlType(def);

    const hasExplicitDefault = Object.hasOwn(defaults, name);
    const isRequired = def.required;

    if (isRequired && !hasExplicitDefault) {
      throw new Error(
        `Missing required default backfill value for field "${name}".`
      );
    }

    if (hasExplicitDefault) {
      const sqlDefault = toSqlLiteral(defaults[name]!, def.type);
      const nullabilityStr = isRequired ? ' NOT NULL' : '';
      const warningType = isRequired ? 'required' : 'nullable';

      warnings.push(
        `Adding ${warningType} column "${name}" — existing rows will be backfilled with ${sqlDefault}`
      );

      // Backfill-then-drop: add with DEFAULT for existing rows, then
      // remove the DEFAULT so future inserts must provide the value.
      statements.push(
        [
          `ALTER TABLE ${WAITLIST_TABLE} ADD COLUMN IF NOT EXISTS ${name} ${type}${nullabilityStr} DEFAULT ${sqlDefault};`,
          `ALTER TABLE ${WAITLIST_TABLE} ALTER COLUMN ${name} DROP DEFAULT;`,
        ].join('\n')
      );
    } else {
      statements.push(
        `ALTER TABLE ${WAITLIST_TABLE} ADD COLUMN IF NOT EXISTS ${name} ${type};`
      );
    }
  }

  const sql = `-- Generated by "pnpm run fields:add"\n\n${statements.join('\n\n')}\n`;
  return { sql, warnings };
}

/**
 * Generates ALTER TABLE statements for edited fields.
 * Called by "pnpm run fields:edit".
 *
 * Handles four kinds of changes:
 *   1. Rename          — ALTER TABLE … RENAME COLUMN old TO new
 *   2. Type change     — ALTER COLUMN name TYPE new_type
 *   3. Length change   — ALTER COLUMN name TYPE VARCHAR(new_length)
 *   4. Required change — ALTER COLUMN name SET/DROP NOT NULL
 *
 */
export function generateEditColumnsMigration(
  edits: FieldEdit[]
): GeneratedMigration {
  if (edits.length === 0) {
    return { sql: '', warnings: [] };
  }

  const statements: string[] = [];
  const warnings: string[] = [];

  for (const edit of edits) {
    const renamed = edit.newName && edit.newName !== edit.name;
    const typeChanged = edit.old.type !== edit.new.type;
    const lengthChanged = edit.old.maxLength !== edit.new.maxLength;
    const requiredChanged = edit.old.required !== edit.new.required;

    if (!renamed && !typeChanged && !lengthChanged && !requiredChanged)
      continue;

    // The column name used in ALTER COLUMN statements after a possible rename
    const effectiveName = renamed ? edit.newName! : edit.name;

    // 1. Rename (must come first)
    if (renamed) {
      warnings.push(
        `Renaming column "${edit.name}" to "${edit.newName}". Update any email templates that reference this column.`
      );
      statements.push(
        `ALTER TABLE ${WAITLIST_TABLE} RENAME COLUMN ${edit.name} TO ${edit.newName};`
      );
    }

    // 2. Type or length change
    if (typeChanged || lengthChanged) {
      const newSqlType = toSqlType(edit.new);
      warnings.push(
        `Changing column "${effectiveName}" type or length may fail if existing data cannot be cast to ${newSqlType}.`
      );
      warnings.push('Back up your data before running this migration.');
      statements.push(
        [
          `-- WARNING: Changing column "${effectiveName}" type or length may fail if existing data cannot be cast to ${newSqlType}.`,
          `--          Back up your data before running this migration.`,
          `ALTER TABLE ${WAITLIST_TABLE} ALTER COLUMN ${effectiveName} TYPE ${newSqlType};`,
        ].join('\n')
      );
    }

    // 3. Required change
    if (requiredChanged) {
      if (edit.new.required) {
        warnings.push(
          `Setting NOT NULL will fail if any existing rows have NULL in "${effectiveName}".`
        );
        statements.push(
          [
            `-- WARNING: Setting NOT NULL will fail if any existing rows have NULL in "${effectiveName}".`,
            `--          Ensure all rows have a value before running this migration.`,
            `ALTER TABLE ${WAITLIST_TABLE} ALTER COLUMN ${effectiveName} SET NOT NULL;`,
          ].join('\n')
        );
      } else {
        // Dropping NOT NULL is always safe — no warning needed
        statements.push(
          `ALTER TABLE ${WAITLIST_TABLE} ALTER COLUMN ${effectiveName} DROP NOT NULL;`
        );
      }
    }
  }

  if (statements.length === 0) {
    return { sql: '', warnings: [] };
  }

  const sql = `-- Generated by "pnpm run fields:edit"\n\n${statements.join('\n\n')}\n`;
  return { sql, warnings };
}

/**
 * Generates ALTER TABLE DROP COLUMN statements.
 * Called by "pnpm run fields:edit" when a user deletes fields.
 */
export function generateDropColumnsMigration(
  fieldNames: string[]
): GeneratedMigration {
  if (fieldNames.length === 0) {
    return { sql: '', warnings: [] };
  }

  const warnings: string[] = [];
  const statements: string[] = [];

  for (const name of fieldNames) {
    warnings.push(
      `Dropping column "${name}" is IRREVERSIBLE. All data in this column will be permanently deleted.`
    );
    statements.push(
      [
        `-- WARNING: Dropping column "${name}" is IRREVERSIBLE.`,
        `--          All data in this column will be permanently deleted.`,
        `--          Back up your data before running this migration.`,
        `ALTER TABLE ${WAITLIST_TABLE} DROP COLUMN IF EXISTS ${name};`,
      ].join('\n')
    );
  }

  const sql = `-- Generated by "pnpm run fields:edit"\n\n${statements.join('\n\n')}\n`;
  return { sql, warnings };
}
